# Generated by Django 4.2.5 on 2023-09-22 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='karbaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('family', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات محصول')),
                ('is_active', models.BooleanField(verbose_name='موجود/ناموجود بودن محصول')),
                ('ratings', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='امتیاز محصول')),
                ('slug', models.SlugField(default='', verbose_name='عنوان در url')),
            ],
        ),
    ]
