# Generated by Django 4.2.5 on 2023-09-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogscategory_alter_product_options_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=400, unique=True, verbose_name='عنوان در url'),
        ),
    ]
