# Generated by Django 4.2.5 on 2023-09-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_productinformation_product_product_informtion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, verbose_name='عنوان تگ')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'نگ محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Product_tag',
            field=models.ManyToManyField(to='blogs.producttag', verbose_name='تگ محصولات'),
        ),
    ]
